name: FRC Build & Test
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2-beta
      - name: FRC Build & Test
        uses: ewpratten/FRC-actions@v1
        with:
          build_mode: 'all'
          cache: gradle
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
